### ISSUE TITLE
Error on listing missing

### ISSUE THREAD

**Issue by abretaud** [baricadr/baricadr#16]
@StephanieRobin has found a BUG§§

Running this command:

`barique file list --missing --max_depth 0 /blablabla/Acyrthosiphon_pisum/`

Getting this traceback on the server:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./baricadr/api/__init__.py", line 77, in list
    files = repo.remote_list(asked_path, missing=missing, max_depth=max_depth, from_root=from_root, full=full)
  File "./baricadr/model/repos.py", line 187, in remote_list
    return self.backend.remote_list(self, path, missing, max_depth, from_root, full)
  File "./baricadr/model/backends.py", line 378, in remote_list
    return self.do_remote_list(repo, path, missing, max_depth, from_root, full, backend_specific_options)
  File "./baricadr/model/backends.py", line 150, in do_remote_list
    remote_list = self.missing_list(path, remote_list, max_depth, repo, full)
  File "./baricadr/model/backends.py", line 167, in missing_list
    for dir_, _, files in self.restricted_walk(path, max_depth):
  File "./baricadr/model/backends.py", line 182, in restricted_walk
    for entry in os.scandir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/blablabla/Acyrthosiphon_pisum/[one_filename_hidden_here]'
```

**Comment by mboudet** [comment]
This error is also not properly managed, since baricadr tries to send an error page instead of json

**Comment by mboudet** [comment]
Cannot reproduce. Is it possible that something was writing in the folder while the process was running?

**Comment by abretaud** [comment]
Probably not, I'll have a look at some point
